[package]
name = "may_rpc"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT"
documentation = "https://docs.rs/may_rpc"
homepage = "https://github.com/Xudong-Huang/may_rpc"
repository = "https://github.com/Xudong-Huang/may_rpc"
keywords = ["rpc", "protocol", "remote", "procedure", "serialize"]
readme = "README.md"
description = "RPC framework for Rust based on coroutine."

[lib]
# crate-type = ["dylib"]

[dependencies]
may = "0.3"
serde = "1"
bincode = "1"
serde_derive = "1"
conetty = { git = "https://github.com/Xudong-Huang/conetty.git" }

[dev-dependencies]
env_logger = "0.4"

