[package]
name = "corpc"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT"
documentation = "https://docs.rs/corpc"
homepage = "https://github.com/Xudong-Huang/corpc"
repository = "https://github.com/Xudong-Huang/corpc"
keywords = ["rpc", "protocol", "remote", "procedure", "serialize"]
readme = "README.md"
description = "RPC framework for Rust based on coroutine."

[lib]
# crate-type = ["dylib"]

[dependencies]
conetty = { git = "https://github.com/Xudong-Huang/conetty.git" }
serde = "1"
serde_derive = "1"
bincode = "0.8"

[dev-dependencies]
env_logger = "0.4"
